### ISSUE TITLE
Copy/paste Error in KHR_DF_TRANSFER_SRGB section

### ISSUE THREAD

**Issue by oddhack** [KhronosGroup/DataFormat#1]
From https://www.khronos.org/bugzilla/show_bug.cgi?id=1463 (which should also be closed when this is taken care of):

On the Kronos Data Spec page, there is a copy paste typo under the
There is a documentation copy/paster typo on this page:
https://www.khronos.org/registry/dataformat/specs/1.1/dataformat.1.1.html

Under the KHR_DF_TRANSFER_SRGB description, the definition of G' when
converting from linear encoding to nonlinear encoding incorrectly refers to the 
R component in the G < 0.0031308 case.

It should be corrected from:

G' = \begin{cases}
      R \times 12.92, & G \leq 0.0031308 \\
      1.055 \times G^{1\over 2.4} - 0.055, & G > 0.0031308
  \end{cases}

To:

G' = \begin{cases}
      G \times 12.92, & G \leq 0.0031308 \\
      1.055 \times G^{1\over 2.4} - 0.055, & G > 0.0031308
  \end{cases}

**Comment by oddhack** [comment]
(agarrard doesn't seem to be in the team yet, so I can't assign to him yet).

**Comment by fluppeteer** [comment]
Fixed in Data Format Specification 1.1 rev 3. Thanks!
