### ISSUE TITLE
Change default branch to 1.3

### ISSUE THREAD

**Issue by MarkCallow** [KhronosGroup/DataFormat#10]
Now that 1.3 is published in the repo please make 1.3 the default branch. I don't know if it is possible to make a PR to do such a thing.

**Comment by lexaknyazev** [comment]
Given that this public repo lacks `master` branch altogether, it would make more sense to have the latest branch (`1.3`) as default. Otherwise, we could have `master` here and follow usual git workflow.

**Comment by MarkCallow** [comment]
I have no objection to renaming 1.3 to master and tagging it 1.3. I'll do it if I have sufficient permissions.

**Comment by MarkCallow** [comment]
I've done it. However the default branch is still set to 1.2. @oddhack do you need me to get signoff to change it to master? Note that the owning WG at present is unclear. How to manage KDFS was to be discussed at the chairs and the board meeting last week.

**Comment by MarkCallow** [comment]
@oddhack, please respond to my previous comment.

**Comment by MarkCallow** [comment]
This has been fixed.
