### ISSUE TITLE
BC7 Table 111 typo

### ISSUE THREAD

**Issue by lewa-j** [KhronosGroup/DataFormat#11]
There is must be a typo in table 111. G1 and B1 should be 7 bytes long, but table says they stored in a bits 29..34 and 42..49, which is 6 and 8 bits long respectively.

![table111](https://user-images.githubusercontent.com/5416122/76230864-64135a00-6235-11ea-9a73-af0787486306.png)

**Comment by MarkCallow** [comment]
Are you talking about Mode 5?

**Comment by lewa-j** [comment]
Yes, mode 5. In the table 109, CB for mode 5 is 7. And according to text right after table 110, each color component is the same size (CB).
And in the table 111, for mode 5, right after G1 and B2, numbers 0..6, meant 7 bit. But issue with offset on the left of them, (29..34, 35..41 and 42..49)

**Comment by MarkCallow** [comment]
Fixed in the just published 1.3.1. Thanks for the report.
