### ISSUE TITLE
MathJax script not loading due to Content-Security-Policy

### ISSUE THREAD

**Issue by kusma** [KhronosGroup/DataFormat#18]
My browser (Firefox) refuses to load the MathJax script when viewing the [latest version of the spec](https://registry.khronos.org/DataFormat/specs/1.2/dataformat.1.2.inline.html), because the server emits this header:

```
Content-Security-Policy: base-uri 'self'; form-action 'self' cdn.khronos.org; script-src 'self' 'unsafe-inline' 'unsafe-eval' cdnjs.cloudflare.com www.googletagmanager.com www.google-analytics.com
```

Here's the error message:

> Content Security Policy: The page’s settings blocked the loading of a resource at https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML (“script-src”).

**Comment by fluppeteer** [comment]
Thank you for the heads-up. Work on an updated KDFS is underway which should be able to resolve this, but I'll have a word with the Khronos webmaster - that's a valid security constraint that is recommended for servers, but I hadn't really been prepared for it breaking the KDFS, so he may or may not be able to fix it without impacting the security of other specs. I hope you can make do with the PDF in the short term, and an update is being prioritised.

**Comment by oddhack** [comment]
If you like we can discuss migrating KDFS to a Vulkan-like approach. I setup KaTeX (much lighter weight than MathJax) to do rendering of math at HTML generation time, and we just publish a copy of KaTeX along with the spec for the needed fonts etc. A bit wasteful of space but entirely self contained for people on airplanes, etc. But that will take a bit of time, so whatever short-term fix James might be able to do would still be needed.

**Comment by KhronosWebservices** [comment]
This issue should now be resolved. Please confirm and close if happy with the current settings.

**Comment by kusma** [comment]
Yep, seems to work fine! Thanks a lot!
