### ISSUE TITLE
Clarify BC7 interpolation

### ISSUE THREAD

**Issue by lexaknyazev** [KhronosGroup/DataFormat#5]
OpenGL extension says (issue 7 [here](https://www.khronos.org/registry/OpenGL/extensions/ARB/ARB_texture_compression_bptc.txt)) that spec requires bit-exact decompression. Yet it doesn't give a formula for getting final pixel values from factors and endpoints. 

Here's an example of possible confusion: https://github.com/GPUOpen-Tools/Compressonator/issues/36.

**Comment by fluppeteer** [comment]
Ah, thanks. I'll seek clarification on hardware implementations for that, and see whether we can tighten the spec; hopefully we trivially can. I'm doing other clean-up triggered by the previous issues, and hope to have an update in the near future.

**Comment by lexaknyazev** [comment]
Here's the proper interpolation formula (resulting numbers match MSDN and AMD implementations):

Integer version:
```
e0, e1 - unsigned integer endpoints [0 .. 255]
weight - unsigned integer interpolation factor (from table 12.1)

((64 - weight) * e0 + weight * e1 + 32) >> 6

returns unsigned integer interpolated value [0 .. 255]
```

Floating-point version (results should be exactly the same as above):
```
floor(ep0 * (1.0 - weight / 64.0) + ep1 * (weight / 64.0) + 0.5)
```

**Comment by fluppeteer** [comment]
Thank you! A fix for this is (and other related issues) is in flight, it's just in a tangled web of other minor tweaks. It should appear soon.

**Comment by fluppeteer** [comment]
So much for "soon", but it should now appear in 1.1.9 and 1.2.1. Thanks!
