### ISSUE TITLE
Cleanup ETC2 spec

### ISSUE THREAD

**Issue by lexaknyazev** [KhronosGroup/DataFormat#7]
1. It would be nice for variables to consistently use italic font throughout the spec. E.g.:
![image](https://user-images.githubusercontent.com/3479527/36987223-48ce0bbe-20b5-11e8-9555-628940fe8759.png)

2. Also, there're some syntax issues (notice backslashes):
![image](https://user-images.githubusercontent.com/3479527/36987452-c3803134-20b5-11e8-967a-abdcf094820b.png)

3. Probably, broken links:
![image](https://user-images.githubusercontent.com/3479527/36987656-524def1e-20b6-11e8-8154-31c261649438.png)
![image](https://user-images.githubusercontent.com/3479527/36987743-87e1d082-20b6-11e8-8492-ca01846764e4.png)

**Comment by fluppeteer** [comment]
The in-progress fixes for this are actually why I've not fixed everything else yet. :-) I'm glad I'm not the only layout pedant. Thank you, I'll make sure I catch all of these too.

**Comment by fluppeteer** [comment]
Actually on it right now. Many many updates, hopefully fixing all this, coming RSN (after inernal Khronos review, admittedly). I'm doing final fix-up. Thank you for your patience. It's amazing how long it takes to do all this...

**Comment by fluppeteer** [comment]
"Make the spec use consistent typography" turns out to have involved pulling on a thread that unravelled half the spec. I hope it's now (1.1.9/1.2.1) more consistent, more legible, and got rid of a disturbingly large number of errors (and I'm sure inserted some exciting new ones).
