### ISSUE TITLE
Errors in Table 113

### ISSUE THREAD

**Issue by lexaknyazev** [KhronosGroup/DataFormat#8]
From `channel_type` description:
> If the **`KHR_DF_SAMPLE_DATATYPE_FLOAT`** bit is set, the sample holds floating point data in a conventional format of 10, 11 or 16 bits, as described in Section 16, “Floating-point formats”, or of 32, or 64 bits as described in [IEEE 754]. Unless a genuine unsigned format is intended, **`KHR_DF_SAMPLE_DATATYPE_SIGNED`** should be set.

Yet in the Table 113, "A single 16-bit floating-point red value, described normally", `channel_type` has no flag bits.

**Comment by fluppeteer** [comment]
Thanks, Alexey. Fixed in the MR currently on the private Khronos gitlab, awaiting internal review.

**Comment by fluppeteer** [comment]
Should be correct as of 1.1.9/1.2.1. Thanks!
